/**
 * @since ___PKG_VERSION___
 * 
 * @packageDocumentation
 */
/*!
 * @maddimathon/design-system-utilities@___CURRENT_VERSION___
 * @license MIT
 */

import { JsonToScss } from '@maddimathon/utility-sass';
import * as z from 'zod';

import * as Schemata from '../00-schemata/index.js';

import { AbstractTokens } from './abstracts/AbstractTokens.js';
import { Tokens_CSS_Transition } from './Tokens/CSS_Transition.js';

export {
    AbstractTokens,
    Tokens_CSS_Transition,
};

/**
 * Generates a complete token object for the design system.
 * 
 * @since ___PKG_VERSION___
 */
export class Tokens extends AbstractTokens<
    z.infer<typeof Schemata.Tokens>,
    Schemata.PartialTokens
> {

    public readonly CSS: {
        transition: Tokens_CSS_Transition;
    };

    public readonly opts: Tokens.Opts;

    public constructor (
        input?: Schemata.PartialTokens,
        opts?: Partial<Tokens.Opts>,
    ) {
        super( input ?? {} );

        this.opts = {
            tokensAsDefault: false,
            ...opts,
        };

        this.CSS = {
            transition: new Tokens_CSS_Transition( input?.css?.transition ?? {} ),
        };
    }

    public export() {

        return {
            CSS: {
                transition: this.CSS.transition.export(),
            },
        };
    }

    public override toSCSS(): string {

        const exp = this.export();

        const vars = {
            transition: JsonToScss.convert( exp.CSS.transition ) || '()',
        };

        const scss: string[] = [
            '// this file is auto-generated by the design-system-utilities CLI',
        ];

        const defaultString = this.opts.tokensAsDefault ? ' !default' : '';

        for ( const t_key in vars ) {
            const _key = t_key as keyof typeof vars;

            scss.push( `$${ _key }: ${ vars[ _key ] }${ defaultString };` );
        }

        return scss.join( '\n\n' );
    }
}

/**
 * Utilities for the {@link Tokens} class.
 * 
 * @since ___PKG_VERSION___
 */
export namespace Tokens {

    export type ScssVarsObj = Omit<z.infer<typeof Schemata.Tokens>, "CSS"> & z.infer<typeof Schemata.Tokens.shape.CSS>;

    /**
     * Options for the {@link Tokens} class.
     * 
     * @since ___PKG_VERSION___
     */
    export interface Opts {
        tokensAsDefault: boolean;
    };
}