/**
 * @since ___PKG_VERSION___
 * 
 * @packageDocumentation
 */
/*!
 * @maddimathon/design-system-utilities@___CURRENT_VERSION___
 * @license MIT
 */

import { JsonToScss } from '@maddimathon/utility-sass';
import * as z from 'zod';

import * as Schemata from '../00-schemata/index.js';

import { AbstractTokens } from './abstracts/AbstractTokens.js';

import { Tokens_Spacing } from './Tokens/Spacing.js';
import { Tokens_Typography } from './Tokens/Typography.js';

import { Tokens_CSS_Border } from './Tokens/CSS_Border.js';
import { Tokens_CSS_Transition } from './Tokens/CSS_Transition.js';

export {
    AbstractTokens,

    Tokens_Spacing,
    Tokens_Typography,

    Tokens_CSS_Border,
    Tokens_CSS_Transition,
};

/**
 * Generates a complete token object for the design system.
 * 
 * @since ___PKG_VERSION___
 */
export class Tokens extends AbstractTokens<
    typeof Schemata.Tokens,
    Tokens.Export,
    Schemata.PartialTokens,
    Tokens.JSON,
    Tokens.ScssVars
> {

    get schema() {
        return Schemata.Tokens;
    }

    public readonly spacing: Tokens_Spacing;
    public readonly typography: Tokens_Typography;

    public readonly CSS: {
        border: Tokens_CSS_Border;
        transition: Tokens_CSS_Transition;
        zIndex: z.infer<typeof Schemata.Tokens.shape.CSS.shape.zIndex>;
    };

    public readonly opts: Tokens.Opts;

    public constructor (
        input?: Schemata.PartialTokens,
        opts?: Partial<Tokens.Opts>,
    ) {
        super( input ?? {} );

        this.opts = {
            tokensAsDefault: false,
            ...opts,
        };

        this.spacing = new Tokens_Spacing( input?.spacing ?? {} );

        this.typography = new Tokens_Typography(
            this.spacing,
            input?.typography ?? {}
        );

        const zIndex = this.schema.shape.CSS.shape.zIndex.parse( input?.css?.zIndex ?? {} );

        this.CSS = {
            border: new Tokens_CSS_Border( input?.css?.border ?? {} ),
            transition: new Tokens_CSS_Transition( input?.css?.transition ?? {} ),
            zIndex,
        };
    }

    public export() {

        return {
            spacing: this.spacing.export(),
            typography: this.typography.export(),

            CSS: {
                border: this.CSS.border.export(),
                transition: this.CSS.transition.export(),
                zIndex: this.CSS.zIndex,
            },
        };
    }

    public override toScssVars(): Tokens.ScssVars {

        const exp = this.export();

        const spacing = this.spacing.toScssVars();

        const line_height = exp.typography.lineHeight;

        return {

            spacing_multiplier: spacing.multiplier,
            margin: spacing.margin,

            font: {
                size: exp.typography.size,
            },

            line_height,

            border: exp.CSS.border,
            transition: exp.CSS.transition,
            z_index: exp.CSS.zIndex,
        };
    }

    public toJSON() {

        return {
            spacing: this.spacing.toJSON(),
            typography: this.typography.toJSON(),

            CSS: {
                border: this.CSS.border.toJSON(),
                transition: this.CSS.transition.toJSON(),
                zIndex: this.CSS.zIndex,
            },
        };
    }

    public override toScss(): string {

        const _vars = this.toScssVars();

        const vars: { [ K in keyof Tokens.ScssVars ]: string; } = {

            spacing_multiplier: JsonToScss.convert( _vars.spacing_multiplier ) || String( this.schema.shape.spacing.shape.multiplier.parse( '' ) ),
            margin: JsonToScss.convert( _vars.margin ) || '()',

            font: JsonToScss.convert( _vars.font ) || '()',

            line_height: JsonToScss.convert( _vars.line_height ) || '()',

            border: JsonToScss.convert( _vars.border ) || '()',
            transition: JsonToScss.convert( _vars.transition ) || '()',
            z_index: JsonToScss.convert( _vars.z_index ) || '()',
        };

        const scss: string[] = [
            '// this file is auto-generated by the design-system-utilities Tokens class',
        ];

        const defaultString = this.opts.tokensAsDefault ? ' !default' : '';

        for ( const t_key in vars ) {
            const _key = t_key as keyof typeof vars;

            scss.push( `$${ _key }: ${ vars[ _key ] }${ defaultString };` );
        }

        return scss.join( '\n\n' );
    }
}

/**
 * Utilities for the {@link Tokens} class.
 * 
 * @since ___PKG_VERSION___
 */
export namespace Tokens {

    export type ScssVars = Omit<z.infer<typeof Schemata.Tokens>, "CSS" | "spacing" | "typography">
        & Omit<z.infer<typeof Schemata.Tokens.shape.CSS>, "zIndex">
        & Omit<z.infer<typeof Schemata.Tokens.shape.spacing>, "multiplier">
        & {
            font: Omit<z.infer<typeof Schemata.Tokens.shape.typography>, "lineHeight">;
            line_height: z.infer<typeof Schemata.Tokens.shape.typography.shape.lineHeight>;
            spacing_multiplier: number;
            z_index: z.infer<typeof Schemata.Tokens.shape.CSS.shape.zIndex>;
        };

    export interface Export extends Omit<z.infer<typeof Schemata.Tokens>, "typography"> {
        typography: Tokens_Typography.Export;
    }

    export interface JSON extends Omit<z.infer<typeof Schemata.Tokens>, "spacing" | "typography"> {
        spacing: Tokens_Spacing.JSON;
        typography: Tokens_Typography.JSON;
    }

    /**
     * Options for the {@link Tokens} class.
     * 
     * @since ___PKG_VERSION___
     */
    export interface Opts {
        tokensAsDefault: boolean;
    };
}