/**
 * @since ___PKG_VERSION___
 * 
 * @packageDocumentation
 */
/*!
 * @maddimathon/design-system-utilities@___CURRENT_VERSION___
 * @license MIT
 */

import { JsonToScss } from '@maddimathon/utility-sass';
import * as z from 'zod';

import { AbstractTokens } from './abstracts/AbstractTokens.js';

import { Tokens_Spacing } from './Tokens/Spacing.js';
import { Tokens_Typography } from './Tokens/Typography.js';

import { Tokens_CSS_Border } from './Tokens/CSS_Border.js';
import { Tokens_CSS_Transition } from './Tokens/CSS_Transition.js';

/**
 * Generates a complete token object for the design system.
 * 
 * @since ___PKG_VERSION___
 */
export class Tokens extends AbstractTokens<
    typeof Tokens.Schema,
    Tokens.Export,
    Tokens.Part,
    Tokens.JSON,
    Tokens.ScssVars
> {

    get schema() {
        return Tokens.Schema;
    }

    public readonly spacing: Tokens_Spacing;
    public readonly typography: Tokens_Typography;

    public readonly CSS: {
        border: Tokens_CSS_Border;
        transition: Tokens_CSS_Transition;

        /**
         * Z-index values for CSS.
         * 
         * Default keys are 'nav', 'settings', 'skipLink'.
         */
        zIndex: z.infer<typeof Tokens.Schema.shape.CSS.shape.zIndex>;
    };

    public readonly opts: Tokens.Opts;

    public constructor (
        input?: Tokens.Part,
        opts?: Partial<Tokens.Opts>,
    ) {
        super( input ?? {} );

        this.opts = {
            tokensAsDefault: false,
            ...opts,
        };

        this.spacing = new Tokens_Spacing( input?.spacing ?? {} );

        this.typography = new Tokens_Typography(
            this.spacing,
            input?.typography ?? {}
        );

        const zIndex = this.schema.shape.CSS.shape.zIndex.parse( input?.css?.zIndex ?? {} );

        this.CSS = {
            border: new Tokens_CSS_Border( input?.css?.border ?? {} ),
            transition: new Tokens_CSS_Transition( input?.css?.transition ?? {} ),
            zIndex,
        };
    }

    public export() {

        return {
            spacing: this.spacing.export(),
            typography: this.typography.export(),

            CSS: {
                border: this.CSS.border.export(),
                transition: this.CSS.transition.export(),
                zIndex: this.CSS.zIndex,
            },
        };
    }

    public toJSON() {

        return {
            spacing: this.spacing.toJSON(),
            typography: this.typography.toJSON(),

            CSS: {
                border: this.CSS.border.toJSON(),
                transition: this.CSS.transition.toJSON(),
                zIndex: this.CSS.zIndex,
            },
        };
    }

    public override toScssVars(): Tokens.ScssVars {

        return {
            ...this.spacing.toScssVars(),
            ...this.typography.toScssVars(),

            border: this.CSS.border.toScssVars(),
            transition: this.CSS.transition.toScssVars(),
            z_index: this.CSS.zIndex,
        };
    }

    public override toScss(): string {

        const _vars = this.toScssVars();

        const vars: { [ K in keyof Tokens.ScssVars ]: string; } = {

            spacing_multiplier: JsonToScss.convert( _vars.spacing_multiplier ) || String( this.schema.shape.spacing.shape.multiplier.parse( '' ) ),
            margin: JsonToScss.convert( _vars.margin ) || '()',

            font: JsonToScss.convert( _vars.font ) || '()',

            line_height: JsonToScss.convert( _vars.line_height ) || '()',

            border: JsonToScss.convert( _vars.border ) || '()',
            transition: JsonToScss.convert( _vars.transition ) || '()',
            z_index: JsonToScss.convert( _vars.z_index ) || '()',
        };

        const scss: string[] = [
            '// this file is auto-generated by the design-system-utilities Tokens class',
        ];

        const defaultString = this.opts.tokensAsDefault ? ' !default' : '';

        for ( const t_key in vars ) {
            const _key = t_key as keyof typeof vars;

            scss.push( `$${ _key }: ${ vars[ _key ] }${ defaultString };` );
        }

        return scss.join( '\n\n' );
    }
}

/**
 * Utilities for the {@link Tokens} class.
 * 
 * @since ___PKG_VERSION___
 */
export namespace Tokens {

    export const Schema = z.object( {

        spacing: Tokens_Spacing.Schema,
        typography: Tokens_Typography.Schema,

        CSS: z.object( {

            border: Tokens_CSS_Border.Schema,
            transition: Tokens_CSS_Transition.Schema,

            zIndex: z.object( {
                nav: z.number().default( 1000 ),
                settings: z.number().default( 9999 ),
                skipLink: z.number().default( 99999 ),
            } ),
        } ),
    } );

    export interface Export extends Omit<z.infer<typeof Schema>, "spacing" | "typography"> {
        spacing: Tokens_Spacing.Export;
        typography: Tokens_Typography.Export;
    }

    export interface JSON extends Omit<z.infer<typeof Schema>, "spacing" | "typography"> {
        spacing: Tokens_Spacing.JSON;
        typography: Tokens_Typography.JSON;
    }

    /**
     * Options for the {@link Tokens} class.
     * 
     * @since ___PKG_VERSION___
     */
    export interface Opts {
        tokensAsDefault: boolean;
    };

    /**
     * The partialized version of the {@link Tokens.Schema} accepted as input.
     *
     * @since ___PKG_VERSION___
     */
    export interface Part {
        spacing?: Partial<Tokens_Spacing.Export>;
        typography?: Partial<Tokens_Typography.Export>;

        css?: {
            border?: Tokens_CSS_Border.Part;
            transition?: Tokens_CSS_Transition.Part;

            zIndex?: Partial<z.infer<typeof Schema.shape.CSS.shape.zIndex>>;
        };
    };

    /**
     * @interface
     */
    export type ScssVars = Omit<z.infer<typeof Schema>, "CSS" | "spacing" | "typography">
        & Tokens_Spacing.ScssVars
        & Tokens_Typography.ScssVars
        & {
            border: Tokens_CSS_Border.ScssVars;
            transition: Tokens_CSS_Transition.ScssVars;
            z_index: z.infer<typeof Schema.shape.CSS.shape.zIndex>;
        };
}